apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pagmondirectorys.madripoor.operator
spec:
  scope: Namespaced
  group: madripoor.operator
  names:
    kind: PagmonDirectory
    plural: pagmondirectorys
    singular: pagmondirectory
    shortNames:
      - pdis
      - pdi
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                directory:
                  type: string
                uuid:
                  type: string
              required:
              - directory
              - uuid